name: Build and Deploy Docker Image - oficina-ineteligente

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Login no Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_504F81AF1F3C4970B919A265D8F23D25 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4983D5B7C40B4C46A04C1B1A49E52147 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D6ECBDD0239C41BE92C99C3D0858CC20 }}

      # 3️⃣ Login no Azure Container Registry (ACR)
      - name: Login to Azure Container Registry
        run: |
          az acr login --name <NOME_DO_SEU_ACR>

      # 4️⃣ Build da imagem Docker
      - name: Build Docker image
        run: |
          docker build \
            -t <NOME_DO_SEU_ACR>.azurecr.io/oficina-ineteligente:latest \
            .

      # 5️⃣ Push da imagem para o ACR
      - name: Push Docker image
        run: |
          docker push <NOME_DO_SEU_ACR>.azurecr.io/oficina-ineteligente:latest